name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cd dlna-server && cargo build --verbose
      - name: Test
        run: cd dlna-server && cargo test --verbose
      - name: Lint
        run: cd dlna-server && cargo clippy --all-targets -- -D warnings
